name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: rustfmt, clippy

      - name: fmt check
        run: cargo fmt --all -- --check

      - name: lint (clippy)
        run: cargo clippy --all -- -D warnings

      - name: Run all tests
        run: cargo test --workspace

      - name: CLI integration tests
        working-directory: cli
        run: cargo test

      - name: Export JSON Schema & verify
        run: |
          cargo run -p threadstone-cli -- schema -o v1/result.schema.json
          git diff --exit-code v1/result.schema.json
